version: '3.9'

services:
  api1:
    build: .
    container_name: api1
    working_dir: /app
    command: bash app.bash
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - 9999:9999

volumes:
  aptcache:
